//! Rust bindings to [zvec], Alibaba's lightweight in-process vector database.
//!
//! The crate has two layers:
//!
//! - [`sys`] — raw FFI generated by `bindgen` from the vendored `c_api.h`.
//!   Every symbol is `unsafe` to call and inherits zvec's C-level ownership
//!   and thread-safety contracts.
//! - A safe layer (types re-exported at the crate root and in submodules)
//!   that wraps the C API in `Result`-returning methods with RAII `Drop`s.
//!
//! # Linking
//!
//! The crate expects a prebuilt `libzvec_c_api` (shipped with the zvec Python
//! wheel, zvec source build, or a system install). `build.rs` locates it via,
//! in order:
//!
//! 1. `ZVEC_LIB_DIR` — explicit directory containing `libzvec_c_api`.
//! 2. `ZVEC_ROOT` — install prefix; uses `$ZVEC_ROOT/lib` (+ `lib64`).
//! 3. `pkg-config` when the `pkg-config` cargo feature is enabled.
//! 4. The system linker's default search paths.
//!
//! Set `ZVEC_STATIC=1` for static linking. Set `ZVEC_INCLUDE_DIR` or
//! `ZVEC_ROOT` to generate bindings against an installed header rather than
//! the one vendored here.
//!
//! # Sharing a `Collection` across threads
//!
//! [`Collection`] is `Send + Sync`, so sharing one across threads is just
//! `Arc<Collection>` — no dedicated `SharedCollection` type is needed.
//! All mutating APIs take `&self` and delegate synchronisation to zvec's
//! own C++ implementation (which uses a shared `std::shared_ptr<Collection>`
//! internally).
//!
//! ```no_run
//! # fn main() -> zvec::Result<()> {
//! use std::sync::Arc;
//! use std::thread;
//! # use zvec::{Collection, CollectionSchema};
//! # let schema: CollectionSchema = unreachable!();
//! let collection = Arc::new(Collection::create_and_open("./coll", &schema, None)?);
//! let handles: Vec<_> = (0..4)
//!     .map(|_| {
//!         let c = Arc::clone(&collection);
//!         thread::spawn(move || c.flush())
//!     })
//!     .collect();
//! for h in handles { let _ = h.join(); }
//! # Ok(())
//! # }
//! ```
//!
//! `Doc`, `VectorQuery`, and `GroupByVectorQuery` are `Send` only — their
//! setters mutate C-side state that isn't documented as concurrency-safe.
//!
//! # Quickstart
//!
//! ```no_run
//! # fn main() -> zvec::Result<()> {
//! use zvec::{
//!     CollectionSchema, FieldSchema, IndexParams, IndexType, MetricType,
//!     DataType, Collection, Doc, VectorQuery,
//! };
//!
//! // Build a schema with one primary-key scalar field and one 3-dim HNSW
//! // vector field.
//! let mut schema = CollectionSchema::new("docs")?;
//!
//! let mut invert = IndexParams::new(IndexType::Invert)?;
//! invert.set_invert_params(true, false)?;
//! let mut id = FieldSchema::new("id", DataType::String, false, 0)?;
//! id.set_index_params(&invert)?;
//! schema.add_field(&id)?;
//!
//! let mut hnsw = IndexParams::new(IndexType::Hnsw)?;
//! hnsw.set_metric_type(MetricType::Cosine)?;
//! hnsw.set_hnsw_params(16, 200)?;
//! let mut emb = FieldSchema::new("embedding", DataType::VectorFp32, false, 3)?;
//! emb.set_index_params(&hnsw)?;
//! schema.add_field(&emb)?;
//!
//! let collection = Collection::create_and_open("./my_coll", &schema, None)?;
//!
//! let mut doc = Doc::new()?;
//! doc.set_pk("doc1")?;
//! doc.add_string("id", "doc1")?;
//! doc.add_vector_fp32("embedding", &[0.1, 0.2, 0.3])?;
//! collection.insert(&[&doc])?;
//! collection.flush()?;
//!
//! let mut q = VectorQuery::new()?;
//! q.set_field_name("embedding")?;
//! q.set_query_vector_fp32(&[0.1, 0.2, 0.3])?;
//! q.set_topk(10)?;
//! let results = collection.query(&q)?;
//! for row in results.iter() {
//!     println!("{:?} score={}", row.pk_copy(), row.score());
//! }
//! # Ok(())
//! # }
//! ```
//!
//! [zvec]: https://github.com/alibaba/zvec

#![cfg_attr(docsrs, feature(doc_cfg))]

pub mod sys;

mod builder;
mod collection;
mod config;
mod doc;
mod error;
mod ffi_util;
mod hybrid;
mod index_params;
mod options;
mod query;
mod query_params;
pub mod rerank;
mod schema;
#[cfg(feature = "serde-json")]
mod serde_json_bridge;
mod stats;
mod types;
mod version;

pub use builder::{CollectionSchemaBuilder, FieldSchemaBuilder, VectorQueryBuilder};
pub use collection::{Collection, DocSet, WriteResult, WriteSummary};
pub use config::{initialize, is_initialized, shutdown, Config, LogConfig};
pub use doc::{Doc, DocRef};
pub use error::{clear_last_error, ErrorCode, Result, ZvecError};
pub use hybrid::HybridSearch;
pub use index_params::IndexParams;
pub use options::CollectionOptions;
pub use query::{GroupByVectorQuery, VectorQuery};
pub use query_params::{FlatQueryParams, HnswQueryParams, IvfQueryParams};
pub use schema::{CollectionSchema, FieldSchema, FieldSchemaRef};
pub use stats::CollectionStats;
pub use types::{DataType, DocOperator, IndexType, LogLevel, LogType, MetricType, QuantizeType};
pub use version::{check_version, version, version_major, version_minor, version_patch};
